version: '3'

volumes:
  elastic_data:
      driver: local

services:
  fastapi_es:
    container_name: fastapi_es
    build:
      context: ./
      # args: 
      #   TEST: Test
    image: udomiljubimca/fastapi_es:1.0
    ports:
      - 8081:8080
    networks:
      - elastic_dev
  elastic_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic_container
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastic_data:/usr/share/elasticsearch/elastic_data
    networks:
      - elastic_dev
    ports:
      - 9200:9200

networks:
  elastic_dev:
    external:
      name: elastic_dev